# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'demo', password: 'hunter12', date_of_birth: '2016-11-02', email: 'demo@gmail.com')
User.create(username: 'thedemo', password: 'hunter12', date_of_birth: '1992-02-02', email: 'gemo@gmail.com')
User.create(username: 'smeli5a', password: 'hunter12', date_of_birth: '1989-02-05', email: 'melisa@gmail.com')
User.create(username: 'kevin', password: 'hunter12', date_of_birth: '1987-09-01', email: 'kev.brimm@gmail.com')
User.create(username: 'ashton', password: 'hunter12', date_of_birth: '1986-05-07', email: 'ahston210z@gmail.com')
User.create(username: 'king-ben', password: 'hunter12', date_of_birth: '1987-05-05', email: 'king_ben@gmail.com')
User.create(username: 'fake_user', password: 'hunter12', date_of_birth: '1980-12-03', email: 'fake@gmail.com')
User.create(username: 'twitch_stream', password: 'hunter12', date_of_birth: '2000-06-11', email: 'twitch@gmail.com')
User.create(username: 'halo2besthalo', password: 'hunter12', date_of_birth: '1995-04-19', email: 'kevin_tv@gmail.com')
User.create(username: 'halo5rules', password: 'hunter12', date_of_birth: '2000-11-02', email: 'h5rules@gmail.com')
User.create(username: 'i_love_halo', password: 'hunter12', date_of_birth: '1999-02-02', email: 'ilovehalo@gmail.com')
User.create(username: 'this_is_halo', password: 'hunter12', date_of_birth: '1980-09-09', email: 'thisishalo@gmail.com')
User.create(username: 'heroes_of_the_storm', password: 'hunter12', date_of_birth: '2005-07-10', email: 'hots@gmail.com')
User.create(username: 'em0_kid', password: 'hunter12', date_of_birth: '1990-08-08', email: 'em0kid@gmail.com')
User.create(username: 'OMGTHISISREAL', password: 'hunter12', date_of_birth: '1992-11-30', email: 'omg@gmail.com')
User.create(username: 'fighting_games', password: 'hunter12', date_of_birth: '2004-04-04', email: 'fightinggames@gmail.com')
User.create(username: 'summit1g', password: 'hunter12', date_of_birth: '1991-01-06', email: 'summit@gmail.com')
User.create(username: 'drdisrespect', password: 'hunter12', date_of_birth: '1980-07-21', email: 'thedoc@gmail.com')
User.create(username: 'ninja', password: 'hunter12', date_of_birth: '1999-11-09', email: 'ninja@gmail.com')
User.create(username: 'grimmy', password: 'hunter12', date_of_birth: '1995-10-19', email: 'grim@gmail.com')
User.create(username: 'summit1g', password: 'hunter12', date_of_birth: '2012-01-01', email: 'appacademy@gmail.com')
User.create(username: 'leet_yeet', password: 'hunter12', date_of_birth: '1991-01-06', email: 'twitchsux@gmail.com')
User.create(username: 'notleetyeet', password: 'hunter12', date_of_birth: '2005-05-09', email: 'kevin@gmail.com')
User.create(username: 'gerardbutler', password: 'hunter12', date_of_birth: '1991-01-06', email: 'demo@hotmail.com')
User.create(username: 'theguywhoplaysironman', password: 'hunter12', date_of_birth: '1991-01-06', email: 'robertdowney@gmail.com')
User.create(username: 'robert_downey', password: 'hunter12', date_of_birth: '1991-01-06', email: 'aa@gmail.com')
User.create(username: 'melisa', password: 'hunter12', date_of_birth: '1991-01-06', email: 'wtfamidoing@gmail.com')
User.create(username: 'kev_cuddy', password: 'hunter12', date_of_birth: '1991-01-06', email: 'itis10pm@gmail.com')
User.create(username: 'kev_cudi', password: 'hunter12', date_of_birth: '1991-01-06', email: 'freebeer@gmail.com')
User.create(username: 'big_byrd', password: 'hunter12', date_of_birth: '1987-12-11', email: 'richard@gmail.com')
User.create(username: 'steve', password: 'hunter12', date_of_birth: '2001-30-02', email: 'steve@gmail.com')
User.create(username: 'benjamin', password: 'hunter12', date_of_birth: '1991-01-06', email: 'ben@gmail.com')
User.create(username: 'meli5a', password: 'hunter12', date_of_birth: '1989-02-05', email: 'meli5a@gmail.com')
User.create(username: 'kevykev', password: 'hunter12', date_of_birth: '1991-01-06', email: 'kevykev@gmail.com')
User.create(username: 'poser', password: 'hunter12', date_of_birth: '1970-04-14', email: 'icnacode@gmail.com')
User.create(username: 'HALO', password: 'hunter12', date_of_birth: '1993-05-16', email: 'bungee@gmail.com')



Game.create(title: 'Yuppie Psycho')
Game.create(title: 'Tekkan 7')
Game.create(title: 'Battletoads')
Game.create(title: 'For Honor')
Game.create(title: 'Zelda a Link to the Past')
Game.create(title: 'Persona 5')
Game.create(title: 'Dark Souls')
Game.create(title: 'Conan Exiles')
Game.create(title: 'Monster Hunter World')
Game.create(title: 'Mario Kart 8')
Game.create(title: 'Diablo 3')
Game.create(title: 'Science and Technology')
Game.create(title: 'War Thunder')
Game.create(title: 'Super Smash Brothers: Melee')
Game.create(title: 'Human: Fall Flat')
Game.create(title: 'Imperator: Rome')
Game.create(title: 'Stardew Valley')
Game.create(title: 'Getting Over It')
Game.create(title: 'Dark Souls 3')
Game.create(title: 'Enter the Gungeon')
Game.create(title: 'Twitch Sings')
Game.create(title: 'Epic 7')
Game.create(title: 'Splitgate')
Game.create(title: 'MLB The Show 2019')
Game.create(title: 'Euro Truck Simulator')
Game.create(title: 'Smite')
Game.create(title: 'Albion Online')
Game.create(title: 'Guild Wars 2')
Game.create(title: 'Battlefield 5')
Game.create(title: 'Super Smash Brothers Ultimate')
Game.create(title: 'Rust')
Game.create(title: 'World of Warships')
Game.create(title: 'osu!')
Game.create(title: 'ARK')
Game.create(title: 'Mario 64')
Game.create(title: 'The Division 2')
Game.create(title: 'The Legend of Zelda: Breath of the Wild')
Game.create(title: 'Day Z')
Game.create(title: 'NBA 2k19')
Game.create(title: 'Borderlands 2')
Game.create(title: 'The Elder Scrolls: Skyrim')
Game.create(title: 'Heroes of the Storm')
Game.create(title: 'Retro Gaming')
Game.create(title: 'Dark Souls 2')
Game.create(title: 'Path of Exiles')
Game.create(title: 'Metal Gear Solid 4')
Game.create(title: 'Last Epoch')
Game.create(title: 'Atlas')
Game.create(title: 'Food and Drink')
Game.create(title: 'Lineage 2')
Game.create(title: 'Chess')
Game.create(title: 'Farming Simulator')
Game.create(title: 'Final Fantasy XIV')
Game.create(title: 'Pokemon Stadium')
Game.create(title: 'God of War')
Game.create(title: 'Starcraft 2')
Game.create(title: 'Undertale')
Game.create(title: 'Mortal Kombat 11')
Game.create(title: 'Rainbow Six: Siege')
Game.create(title: 'Jump King')
Game.create(title: 'Dead by Daylight')
Game.create(title: 'Magic: The Gathering')
Game.create(title: 'Days Gone')
Game.create(title: 'Overwatch')
Game.create(title: 'FIFA 2019')
Game.create(title: 'Apex Legends')
Game.create(title: 'Defenders of the Ancienct: 2')
Game.create(title: 'Hearthstone')
Game.create(title: 'World of Warcraft')
Game.create(title: 'Just Chatting')
Game.create(title: 'PLAYERUNKNOWNS BATTLEGROUNDS')
Game.create(title: 'League of Legends')
Game.create(title: 'Fortnite')
Game.create(title: 'Counter Strike: Global Offensive')
Game.create(title: 'Rocket League')

